const Data = {
  vowels: {
    'a': true,
    'e': true,
    'i': true,
    'o': true,
    'u': true,
    'y': true,
    'au': false,
    'eu': false,
    'ou': false,
    'ai': false,
    'ei': false,
    'oi': false,
    // 'é': false,
    // 'è': false,
    // 'ê': false,
    // 'ë': false,
    // 'à': false,
    // 'â': false,
    // 'â': false,
    // 'î': false,
    // 'ï': false,
  },
  consonants: {
    'b': false,
    'c': false,
    'ch': false,
    'd': false,
    'f': false,
    'g': false,
    'h': false,
    'j': false,
    'k': false,
    'l': false,
    'm': false,
    'n': false,
    'p': false,
    'ph': false,
    'q': false,
    'r': true,
    's': true,
    't': false,
    'v': false,
    'w': false,
    'x': false,
    'z': false,
  },
};

export default Data;
