const Data = {
  vowels: {
    'a': false,
    'e': false,
    'i': false,
    'o': false,
    'u': false,
    'y': false,
    // 'é': false,
    // 'è': false,
    // 'ê': false,
    // 'ë': false,
    // 'à': false,
    // 'â': false,
    // 'â': false,
    // 'î': false,
    // 'ï': false,
  },
  consonants: {
    'b': false,
    'c': false,
    'ch': false,
    'd': false,
    'f': false,
    'g': false,
    'h': false,
    'j': false,
    'k': false,
    'l': false,
    'm': false,
    'n': false,
    'p': false,
    'q': false,
    'r': false,
    's': false,
    't': false,
    'v': false,
    'w': false,
    'x': false,
    'z': false,
  },
};

export default Data;
